-- Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nulls")
require("plugins.autopair")
require("plugins.autotag")
require("plugins.comments")
require("plugins.lualine")
require("plugins.gitsigns")
require("plugins.dashboard")
